language: ruby
rvm: 2.5.1
services: postgresql
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script: bundle exec rspec spec/
env:
  global:
  - secure: SGiVMWZW/B8sPz6/wcvRnHFPRnj0NVkn8bWM4cRcu/yYDByMkjaRgMSpnBnfzVsL/L7cRvd+sA5S+DwobHVB5HNLMbhJu1BrSdrQNhPpvY/YJJ8o5OVI9mdgvZpEEuy0xVGV2ek2HWHsxdky0h70LZwyNQ9wrQBmQLMYkD1SFYB1d4MXisbM1RcDhD3+LCKBgR882SziAV7pyTzv0lLpDC+MApNvhBrbptpxdsfnykDBh48GMojtuVPTxhC/iHXsspl0aT7oTT+K+6MW2XbjZFBvCfMCEQ3OAQECjQEi0eOY7YlLCvC73df0+Gh+bmtB96IKUL6zA43G6gUY1k7XIvZIuxZkPBAmaX6qjsvG43TmqEeYhx6AHz+9KAh/7OwP+UUcW+PMfT9lAA/yjsREhT7N4AUhvC2BmtEmr+H6bJwt/FApGZL5wf9ebgFBa/ep2Ahz7mxeopSNyrJkTVLmDUZ10eNiTF5kjmmCv4ClI9W9CQ53K+olTwGmyf2M49S0t0KoDgDKFCa3alhYDbCMxzHPUGKNknD5E9PN6HwL+i7a9ErJx4RTMV7MSUriF//+onoVBrcSpsfpMfCIpRaTCwPfGM2VueLvoFUOz76JOFv8zSowrcsMwBFhKW/xrz8p7286bEsIN+0kIpZZFPecs6Xfxo9DK69gDWOQZPFHcvI=
  - secure: fnkSOLV3dD04eLY4qTNymGPMFI3K+WFImSkJ4ta5OFH3eNPv+BNN05nKyqo78cc1HtMOaNmxzadvjQSVZjz4X20frvu3yCwxK1S8A7ixi/rXPrVbXUYGy55OVxE1g1CsStMj/i5SpZ/lhFwDGQjA+kQiDntn8nnWP6QuJmc10z/Qty5fQJ7iLuXyqvYLNoOkzdKdQ7AsR2WnCgu7shMwyMG+GMUWJQMtEBVry2WjhOOtMjzqcZyedEn7Hh5OeJgbbqRDPAcQYF175hxw64Blrk+vHy0c34Gske4+7tG/XbBgGxIUMMO5juzhUPkuV+oeiV5dDjQet57VCftTYRiE+aB/dqrs6K7rP8Mc1yoSkjbVQQPIHipIPnXl/FsnchtyIJ+6wnEylHLN/DNwIy/LmV9nSbBrxBsyjljyc9JhzOmU/M5nm1cXLtVIyAh90gvwJEWRLMICmLyC5dO7HWpnnQcLtS/ZJv4C6wzS0OY0uuKeSntorBCU/WXOX91IjduSnhT84+Iz6XMl4aJXMikl40cF+ktDKm2Q23LU4tYM7l5hyj3EpX2NwLchrw4EG5Fdp84P2Hn8OIg5vPx4b4fd4Ds8Zf/DgKWuHZbMjeUZhIWIkvWFpBWiUpWg9tHq8IjjqG6AzrmUNp7x9TEdD2HjwgwxBtjkSlC4OVYSLqBaJfc=
